### ISSUE TITLE
Red tide occurrences in TB

### ISSUE THREAD

**Issue by esherwoo77** [tbep-tech/piney-point-manu#10]
https://github.com/tbep-tech/piney-point-manu/blob/7f88eae843f2325438546098b44cdd109ee745d4/manu-draft.Rmd#L303 . Observations (very low) within lower Tampa Bay occurred as early as April 13th. 'Low' observations were observed on 4/21 in Lower Tampa Bay (gulf side of Skyway). 'Low' observation observed right off Port Manatee on 5/18. 'Medium' bloom concentrations didn't present in Lower Tampa Bay until 5/24 (right off Joe Island bay side of Skyway).

https://www.ncei.noaa.gov/maps/habsos/maps.htm

**Comment by fawda123** [comment]
Corrected in your edits, thanks.
