### ISSUE TITLE
Appropriate location info?

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/piney-point-manu#4]
https://github.com/tbep-tech/piney-point-manu/blob/230d4bafc1d53abfc2d02cd9766aca146386df29/manu-draft.Rmd#L80
NBD, Palmetto is the postal location, but the facility is actually in unincorporated Manatee County.

**Comment by esherwoo77** [comment]
Yes, I think that city reference is fine. A lat/long can be substituted, if a reviewer asks for further details on location.
