### ISSUE TITLE
Follow up benthic monitoring

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/piney-point-manu#5]
Happened in September 2021, right? https://github.com/tbep-tech/piney-point-manu/blob/7e6018745d7c81a7f6eaaa3009356d63737eb930/manu-draft.Rmd#L353

**Comment by Gmangrove** [comment]
Apologies for not noticing the original text earlier, will edit this week. Thoughts:

- 2nd set of samples was collected in September (per D.Karlen), but it'll likely be a few months before the benthic data is analyzed. I think PP data has been prioritized, will double-check.
- The TBBI officially gives grades of Healthy, Intermediate, and Degraded, which are analagous to the green, yellow & red.
- TBBI scores are only based on benthic infauna, it doesn't say anything about the sediments per se (silt/clay, contaminants)
