### ISSUE TITLE
does HRK still maintain ownership of PP or did that recently change?

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/piney-point-manu#6]
Final line of the history info (now in supplement) states that HRK still has ownership of the site.  Has this changed? I recall hearing it did, but wanted to verify.
 https://github.com/tbep-tech/piney-point-manu/blob/cfbe3d877819771510c249007a0ac0da67f866b3/supplement.Rmd#L42

**Comment by emseabee** [comment]
HRK is still the owner. The receivership has been finalized, but that does not transfer ownership. The receiver has a legal obligation to act in the interest of all parties associated with the litigation.
