### ISSUE TITLE
ready for check before back to co-authors

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/piney-point-manu#7]
@esherwoo77 manuscript and supplement are ready for your review before we send it back to co-authors.  Here's a quick summary of the changes.  Basically I just need a gut check for the current content, no heavy editing needed unless you think it's warranted.

* Expanded red tide analysis to include wind/precip, added more explanation to discussion
* Added more inclusive plots showing phyto, red tide, nutrients, macro relationships
* Evaluated seagrass and macroalgae abundances "to be sure"
* Multi-comp test for water quality is seasonally detrended
* Added GAM seasonal trend predictions to replace weekly boxplots
* Removed PCA and correlation matrices
* Added supplement figs/tables
* Added text in methods describing role of USF model in guiding sampling
* Numerous edits from multiple co-authors

**Comment by esherwoo77** [comment]
@fawda123 : This looks really good the addition of the GAM and ordination figure put the results in much better context and the discussion of the progression of the ecosystem response is much improved. Thanks for pulling this together and integrating comments so quickly. Well done, as usual!

FYI and versioning history ... I pushed some suggested tweaks throughout the text, directly into the RMD file on 11/11. I'll review the supplement next.
