### ISSUE TITLE
Gypstack statements.

### ISSUE THREAD

**Issue by esherwoo77** [tbep-tech/piney-point-manu#8]
https://github.com/tbep-tech/piney-point-manu/blob/45d335914216cbfc6118b9e65a55adeb1dc96b3c/manu-draft.Rmd#L70 . The statement: 

"Currently, seventeen phosphogypsum stacks exist in the Tampa Bay watershed with no comprehensive, long-term plan for closure or disposal of waste ... " is technically accurate, but it convolutes the fact that the active facilities are operating under a permit with defined conditions for storage and handling of the material with other assurances for final closure of the facilities.

**Comment by fawda123** [comment]
I see you edited the statement in the draft already, closing the issue now.
